In [3]:
import numpy as np

Adding together two simple matrices
Example is a 4x3 matrix

In [5]:
a = np.array([[[1,2,3],[4,5,6]],[[1,1,1],[2,2,2]]])
b = np.array([[[1,2,4],[5,4,6]],[[1,4,5],[8,2,4]]])

a+b

array([[[ 2,  4,  7],
        [ 9,  9, 12]],

       [[ 2,  5,  6],
        [10,  4,  6]]])

Multiply together two simple matrices
Example is a 2x3 and a 3x2 (both matrices are in the correct form i.e. mxn and nxo)

In [7]:
c = np.array([[5,21,6],[11,8,62]])
d = np.array([[2,5],[3,8],[10,9]])

np.dot(c,d)

array([[133, 247],
       [666, 677]])

Multiply together two simple vectors and dealing with shapes

In [13]:
e = np.array([2,3])
f = np.array([-2,-3])

np.dot(e,f)

e.shape
e.reshape(2,1)

array([[2],
       [3]])

Example of a tensor with depth = 3; row = 2; column = 2

In [19]:
s=np.array([[[1,2],[3,4]],[[5,6],[7,8]],[[9,10],[11,12]]])
m=np.array([[[-2,-2],[3,14]],[[15,-2],[7,8]],[[29,10],[21,32]]])

s.shape
s[0]+m[1]

array([[16,  0],
       [10, 12]])

Transposing a matrix and reshaping (note that transposing matrix g equals the original matrix)

In [73]:
g=np.array([[1,1,4],[1,0,2],[4,2,5]])
g

array([[1, 1, 4],
       [1, 0, 2],
       [4, 2, 5]])

In [86]:
np.dot(g,g.T)

array([[18,  9, 26],
       [ 9,  5, 14],
       [26, 14, 45]])

Another example of transpose

In [80]:
C = np.array([[4,-5],[8,12],[-2,-3],[19,0]])
C

array([[ 4, -5],
       [ 8, 12],
       [-2, -3],
       [19,  0]])

In [82]:
C.T

array([[ 4,  8, -2, 19],
       [-5, 12, -3,  0]])

....

In [88]:
N = np.array([[12,3,2],[10,8,6]])
M = np.array([[1,4,2],[0,0,1],[1,0,0]])
P = np.array([[5,6,7],[90,11,32],[5,6,19]])

np.dot(N,M)

array([[14, 48, 27],
       [16, 40, 28]])

In [90]:
np.dot(N,M)+5

array([[19, 53, 32],
       [21, 45, 33]])

This operation does not work because the shape of the NxM matrix is not the same as the 5*P matrix

In [92]:
np.dot(N,M)+5*P

ValueError: operands could not be broadcast together with shapes (2,3) (3,3) 

Multiplation of two unit vectors that are orthogonal to each other

In [94]:
h = np.array([1,0])
i = np.array([0,1])

np.dot(h,i)

0

Multiplication of two unit vectors in the same direction just increases the magnitude

In [102]:
j = np.array([1,1])
k = np.array([1,1])

np.dot(j,k)

2

An example of set time of activity per day 3 times a day for two days

In [13]:
two_days = np.array([[24,45,15],[12,34,53]])
two_days

array([[24, 45, 15],
       [12, 34, 53]])

In [43]:
total_per_day = np.array([[1,1,1]])
total_per_day.shape
total_per_day_s = total_per_day.reshape(1,3)

#np.dot(total_per_day_s, two_days)

total_per_day_s



array([[1, 1, 1]])

Calculating the total time of activities per day using matrix multiplication. The second matrix is transposed to get the two matrices in the right shape for multiplication i.e. 1xn and nx2 where n = 3

In [45]:
np.dot(total_per_day_s,two_days.T)

array([[84, 99]])

Converting minutes of the two day activity to seconds (Scalar times a matrix)

In [51]:
[60]*two_days

array([[1440, 2700,  900],
       [ 720, 2040, 3180]])